### ISSUE TITLE
fonts.gstatic.com preconnect hint when using local fonts

### ISSUE THREAD

**Issue by cuu508** [fontsplugin/plugin#23]
I've configured Fonts Plugin to host fonts locally. This works, but in the rendered page I see this:

    <link href="https://fonts.gstatic.com" crossorigin="" rel="preconnect">

I think it is produced here: https://github.com/fontsplugin/plugin/blob/master/class-olympus-google-fonts.php#L136

Is there a way to avoid this?

Thanks!

**Comment by cuu508** [comment]
Grepping for "fonts.gstatic.com" in the theme source turns up no results...

**Comment by DannyCooper** [comment]
Hi @cuu50,

You are right, sorry about that. I'll release a fix in the next 24-48 hours.

**Comment by cuu508** [comment]
Sure thing – done!

**Comment by cuu508** [comment]
Fixed in ec57164c8a5f744caf5482a3843f0da120f73efe – thank you @DannyCooper!
